apiVersion: v1
kind: PersistentVolume
metadata:
  name: taskmaster-pv
spec:
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain
  storageClassName: taskmaster-storage-class
  hostPath:  
    path: "/mnt/data/taskmaster"  