apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskmaster-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: taskmaster-storage-class